# Generated by Django 3.0.8 on 2020-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static')),
                ('desc', models.TextField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
